DROP TABLE IF EXISTS art CASCADE;
DROP TABLE IF EXISTS token CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS artTags CASCADE;
DROP TABLE IF EXISTS userLikes CASCADE;

CREATE TABLE tags (
    tag_id INT GENERATED ALWAYS AS IDENTITY,
    tag VARCHAR (100) NOT NULL,
    PRIMARY KEY (tag_id)
);

CREATE TABLE Users (
    user_id INT GENERATED ALWAYS AS IDENTITY,
    username VARCHAR(50) UNIQUE NOT NULL ,
    password VARCHAR(255) NOT NULL,
    profile_url VARCHAR(1000) NOT NULL,
    bio VARCHAR(500),
    contact_url VARCHAR(1000),
    PRIMARY KEY(user_id)
);

CREATE TABLE art (
    art_id INT GENERATED ALWAYS AS IDENTITY,
    user_id INT NOT NULL,
    title VARCHAR(50) NOT NULL,
    description VARCHAR(10000),
    likes INT NOT NULL,
    url VARCHAR(1000) NOT NULL,
    PRIMARY KEY(art_id),
    FOREIGN KEY (user_id) REFERENCES Users(user_id)
);

CREATE TABLE artTags (
    art_id INT,
    tag_id INT,
    PRIMARY KEY (art_id, tag_id),
    FOREIGN KEY (art_id) REFERENCES art(art_id),
    FOREIGN KEY (tag_id) REFERENCES tags(tag_id)
);

CREATE TABLE userLikes (
    user_id INT,
    art_id INT,
    PRIMARY KEY (art_id, user_id),
    FOREIGN KEY (art_id) REFERENCES art(art_id),
    FOREIGN KEY (user_id) REFERENCES Users(user_id)
);

CREATE TABLE comments (
    comment_id INT GENERATED ALWAYS AS IDENTITY,
    art_id INT NOT NULL,
    user_id INT NOT NULL,
    content VARCHAR(4000),
    PRIMARY KEY(comment_id),
    FOREIGN KEY (art_id) REFERENCES art(art_id)
);

CREATE TABLE token (
    token_id INT GENERATED ALWAYS AS IDENTITY,
    user_id INT NOT NULL,
    token CHAR(36) UNIQUE NOT NULL,
    PRIMARY KEY (token_id),
    FOREIGN KEY (user_id) REFERENCES Users(user_id)
);

INSERT INTO tags (tag)
VALUES 
    ('Painting'),
    ('Drawing'),
    ('Digital'),
    ('Photography'),
    ('Animals'),
    ('Landscapes'),
    ('Portraits'),
    ('Abstract'),
    ('Historic Artists'),
    ('Active Artists'),
    ('Still Life'),
    ('Sculpture');

INSERT INTO Users (username, password, profile_url)
VALUES
    ('VanGogh', '$2b$10$.HLNUQ9PqjWw/21a8TRj4uDXhxGDLx0j/zpzcTpzLbo1BvZNah6Dq', 'https://storage.googleapis.com/artvista-images/vangogh/vangogh_profile.jpg'),
    ('L.DaVinci', '$2b$10$.HLNUQ9PqjWw/21a8TRj4uDXhxGDLx0j/zpzcTpzLbo1BvZNah6Dq', 'https://storage.googleapis.com/artvista-images/davinci/davinci_profile.jpg'),
    ('J.Pollock', '$2b$10$.HLNUQ9PqjWw/21a8TRj4uDXhxGDLx0j/zpzcTpzLbo1BvZNah6Dq', 'https://storage.googleapis.com/artvista-images/pollock/jpollock_profile.jpg'),
    ('A.Warhol', '$2b$10$.HLNUQ9PqjWw/21a8TRj4uDXhxGDLx0j/zpzcTpzLbo1BvZNah6Dq', 'https://storage.googleapis.com/artvista-images/warhol/awarhol_profile.jpg'),
    ('Michelangelo', '$2b$10$.HLNUQ9PqjWw/21a8TRj4uDXhxGDLx0j/zpzcTpzLbo1BvZNah6Dq', 'https://storage.googleapis.com/artvista-images/michelangelo/michelangelo_profile.jpg'),
    ('P.Picasso', '$2b$10$.HLNUQ9PqjWw/21a8TRj4uDXhxGDLx0j/zpzcTpzLbo1BvZNah6Dq', 'https://storage.googleapis.com/artvista-images/picasso/picasso_profile.jpg'),
    ('user', '$2b$10$gFWE8CNP/t2mlonOC34aA.f7Gr5bi.ZG4tB6hlnRmuCCkyr9k7wIC', 'https://storage.googleapis.com/artvista-images/default_profile.png');

INSERT INTO art (user_id, title, description, likes, url)
VALUES
    (1, 'Starry Night', 'A mesmerizing depiction of a starry night sky over a tranquil village, showcasing swirling patterns of stars and a crescent moon. (1889)', 1889, 'https://storage.googleapis.com/artvista-images/vangogh/starrynight.jpg'),
    (1, 'Sunflowers', 'A series of paintings capturing vibrant arrangements of sunflowers in different stages of bloom, showcasing their beauty and vitality. (1888-1889)', 1852, 'https://storage.googleapis.com/artvista-images/vangogh/sunflowers.jpg'),
    (1, 'Irises', 'Van Gogh''s vivid portrayal of irises in a garden, featuring bold colors and expressive brushwork. (1889)', 2239, 'https://storage.googleapis.com/artvista-images/vangogh/irises.jpg'),
    (1,'The Bedroom', 'A depiction of van Gogh''s own bedroom in various shades of blue, conveying a sense of comfort and solitude. (1888)', 1081, 'https://storage.googleapis.com/artvista-images/vangogh/bedroom.jpg'),
    (1, 'Café Terrace at Night', 'A lively scene of a café terrace illuminated with warm, glowing light under a starry sky. (1888)', 1854, 'https://storage.googleapis.com/artvista-images/vangogh/cafe%20terrace.jpg'),
    (1, 'Self-Portrait with Bandaged Ear', 'A self-portrait created after the artist famously cut off part of his ear, showing van Gogh''s resolute gaze. (1889)', 5109, 'https://storage.googleapis.com/artvista-images/vangogh/self%20portrait%20bandage.jpg'),
    (1, 'Wheatfield with Crows', 'A poignant landscape painting depicting a wheat field with dramatic, swirling crows overhead. (1890)', 1225, 'https://storage.googleapis.com/artvista-images/vangogh/Vincent_Van_Gogh_-_Wheatfield_with_Crows.jpg'),
    (1, 'Almond Blossoms', 'A series of paintings featuring blossoming almond branches against a clear blue sky, symbolizing new beginnings and hope. (1890)', 2575, 'https://storage.googleapis.com/artvista-images/vangogh/almond%20blossom.jpg'),
    (2, 'Mona Lisa', 'A renowned portrait of a woman with a mysterious smile, set against a landscape backdrop. (1503-1506)', 1480, 'https://storage.googleapis.com/artvista-images/davinci/mona_lisa.jpg'),
    (2, 'Vitruvian Man', 'A drawing illustrating the proportions of the human body, reflecting da Vinci''s interest in anatomy. (c. 1490)', 5264, 'https://storage.googleapis.com/artvista-images/davinci/vitruvian_man.png'),
    (2, 'Lady with an Ermine', 'A portrait of a woman holding an ermine, showcasing da Vinci''s mastery of detail and expression. (1489-1490)', 1984, 'https://storage.googleapis.com/artvista-images/davinci/ermine.jpg'),
    (2, 'The Baptism of Christ', 'A collaborative work with Verrocchio, featuring da Vinci''s skillful execution of the angel in the painting. (1472-1475)', 1529, 'https://storage.googleapis.com/artvista-images/davinci/baptism.jpg'),
    (2, 'Annunciation', 'A painting depicting the angel Gabriel announcing to the Virgin Mary that she will conceive Jesus. (1472-1475)', 8258, 'https://storage.googleapis.com/artvista-images/davinci/annunciation.jpg'),
    (2, 'Salvator Mundi', 'A painting of Christ as the Savior of the World, showcasing da Vinci''s masterful handling of light and shadow. (c. 1500)', 2689, 'https://storage.googleapis.com/artvista-images/davinci/mundi.jpg'),
    (2, 'Madonna of the Rocks', 'Two versions exist, both portraying the Madonna, Christ, and John the Baptist in a rocky setting. (1483-1486, 1495-1508)', 1365, 'https://storage.googleapis.com/artvista-images/davinci/rocks.jpg'),
    (2, 'The Last Supper', 'A famous fresco depicting Jesus Christ and his disciples during the Last Supper. (1495-1498)', 2034, 'https://storage.googleapis.com/artvista-images/davinci/last%20supper.jpg'),
    (3, 'Autumn Rhythm (Number 30)', 'A monumental abstract painting characterized by rhythmic drips and splashes of paint. (1950)', 1480, 'https://storage.googleapis.com/artvista-images/pollock/autumn%20rhythm%2030.jpg'),
    (3, 'Blue Poles: Number 11, 1952', 'A large-scale painting featuring vibrant blue poles amidst a complex web of drips and lines. (1952)', 5264, 'https://storage.googleapis.com/artvista-images/pollock/autumn%20rhythm%2030.jpg'),
    (3, 'Convergence', 'An energetic composition of interwoven colors and spontaneous brushstrokes, exemplifying Pollock''s action painting. (1952)', 1984, 'https://storage.googleapis.com/artvista-images/pollock/convergence.jpg'),
    (3, 'Lavender Mist: Number 1, 1950', 'A mesmerizing painting featuring layers of lavender and other colors, evoking a sense of depth and movement. (1950)', 1529, 'https://storage.googleapis.com/artvista-images/pollock/lavender%20mist.jpg'),
    (3, 'Number 8, 1950', 'A dynamic piece characterized by chaotic swirls and splatters of paint, showcasing Pollock''s unique style. (1950)', 8258, 'https://storage.googleapis.com/artvista-images/pollock/number%208.png'),
    (3, 'One: Number 31, 1950', 'A large-scale canvas filled with intricate layers of lines, dots, and drips in various colors. (1950)', 2689, 'https://storage.googleapis.com/artvista-images/pollock/number%2031.jpg'),
    (3, 'Shimmering Substance', 'An abstract work known for its intricate layers of paint that create a shimmering effect on the canvas. (1946)', 1365, 'https://storage.googleapis.com/artvista-images/pollock/shimmering.jpg'),
    (3, 'The Deep', 'A painting featuring tangled, layered lines and forms in black and white, representing Pollock''s exploration of depth. (1953)', 2034, 'https://storage.googleapis.com/artvista-images/pollock/deep.jpg'),
    (4, 'Campbell''s Soup Cans', 'A series of 32 paintings depicting Campbell''s Soup cans in various flavors, an iconic representation of consumer culture. (1962)', 1480, 'https://storage.googleapis.com/artvista-images/warhol/soup.jpg'),
    (4, 'Marilyn Diptych', 'A silkscreen painting featuring multiple images of Marilyn Monroe, exploring themes of fame and mortality. (1962)', 5264, 'https://storage.googleapis.com/artvista-images/warhol/marilyn.jpg'),
    (4, 'Eight Elvises', 'A painting depicting eight identical images of Elvis Presley, reflecting Warhol''s fascination with celebrity culture. (1963)', 1984, 'https://storage.googleapis.com/artvista-images/warhol/Eight_Elvises.jpg'),
    (4, 'Brillo Boxes', 'Sculptural replicas of Brillo soap pad boxes, blurring the lines between art and everyday consumer objects. (1964)', 1529, 'https://storage.googleapis.com/artvista-images/warhol/brillo%20box.png'),
    (4, 'Triple Elvis', 'A silkscreen painting portraying three identical images of Elvis Presley in a cowboy attire. (1963)', 8258, 'https://storage.googleapis.com/artvista-images/warhol/triple%20elvis.jpg'),
    (4, 'Flowers', 'A series of brightly colored screenprints featuring repeated images of flowers, exploring themes of beauty and mass production. (1964)', 2689, 'https://storage.googleapis.com/artvista-images/warhol/flowers.png'),
    (4, 'Electric Chair', 'A series of paintings portraying the electric chair, exploring themes of death and media imagery. (1963-1967)', 1365, 'https://storage.googleapis.com/artvista-images/warhol/chair.png'),
    (4, 'Self-Portrait', 'Various self-portraits created using different mediums, showcasing Warhol''s fascination with self-representation. (1963-1986)', 2034, 'https://storage.googleapis.com/artvista-images/warhol/self.jpg'),
    (5, 'David', 'A renowned marble sculpture of the biblical hero David, showcasing Michelangelo''s mastery of human anatomy. (1501-1504)', 1480, 'https://storage.googleapis.com/artvista-images/michelangelo/david.jpg'),
    (5, 'Sistine Chapel Ceiling', 'A masterpiece fresco depicting various scenes from the Book of Genesis, including the iconic Creation of Adam. (1508-1512)', 5264, 'https://storage.googleapis.com/artvista-images/michelangelo/Sistine_ceiling.jpg'),
    (5, 'Pieta', 'A marble sculpture portraying the Virgin Mary holding the body of Jesus, displaying emotional depth and technical skill. (1498-1499)', 1984, 'https://storage.googleapis.com/artvista-images/michelangelo/pieta.jpg'),
    (5, 'The Last Judgment', 'A fresco on the altar wall of the Sistine Chapel, depicting the Second Coming of Christ and final judgment. (1536-1541)', 1529, 'https://storage.googleapis.com/artvista-images/michelangelo/last_judgement.jpg'),
    (5, 'Moses', 'A marble sculpture portraying the biblical figure Moses with commanding intensity and intricate details. (1513-1515)', 8258, 'https://storage.googleapis.com/artvista-images/michelangelo/moses.jpg'),
    (5, 'The Creation of Adam', 'A famous fresco panel illustrating the moment when God gives life to Adam, touching fingers. (1508-1512)', 2689, 'https://storage.googleapis.com/artvista-images/michelangelo/adam.jpg'),
    (5, 'Dying Slave', 'A sculpture depicting a male figure in a state of struggle and physical tension, part of a series for Pope Julius II''s tomb. (1513-1516)', 1365, 'https://storage.googleapis.com/artvista-images/michelangelo/dying%20slave.jpg'),
    (5, 'Tomb of Giuliano de'' Medici', 'A sculptural masterpiece featuring a reclining statue of Giuliano de'' Medici surrounded by allegorical figures. (1526-1531)', 2034, 'https://storage.googleapis.com/artvista-images/michelangelo/giuliano.png'),
    (6, 'Les Demoiselles d''Avignon', 'A groundbreaking painting depicting five nude female figures with angular and fragmented forms. (1907)', 1480, 'https://storage.googleapis.com/artvista-images/picasso/Avignon.jpg'),
    (6, 'Guernica', 'A powerful mural-sized painting portraying the horrors of the Spanish Civil War, featuring distorted figures and symbolism. (1937)', 5264, 'https://storage.googleapis.com/artvista-images/picasso/guernica.jpg'),
    (6, 'The Weeping Woman', 'A series of paintings portraying a woman in deep anguish and sorrow, often linked to Picasso''s personal life. (1937)', 1984, 'https://storage.googleapis.com/artvista-images/picasso/weeping%20woman.jpg'),
    (6, 'The Old Guitarist', 'A haunting depiction of a blind and impoverished musician hunched over his guitar, rendered in blue tones. (1903-1904)', 1529, 'https://storage.googleapis.com/artvista-images/picasso/guitarist.jpg'),
    (6, 'Seated Woman (Dora Maar)', 'A series of portraits of Dora Maar, a prominent figure in Picasso''s life, captured in various styles and moods. (1938)', 8258, 'https://storage.googleapis.com/artvista-images/picasso/seated%20woman.jpg'),
    (6, 'Les Femmes d''Alger', 'A series of paintings inspired by Delacroix''s work, featuring abstract and vivid depictions of Algerian women. (1954-1955)', 2689, 'https://storage.googleapis.com/artvista-images/picasso/femmes.jpg'),
    (6, 'Bull Series', 'A sequence of lithographs depicting the transformation of a bull from detailed realism to simple abstract forms. (1945)', 1365, 'https://storage.googleapis.com/artvista-images/picasso/bull%20series.jpg'),
    (6, 'Three Musicians', 'A colorful and playful painting portraying three figures, combining elements of Cubism and Synthetic Cubism. (1921)', 2034, 'https://storage.googleapis.com/artvista-images/picasso/3%20musicians.jpg');
    
INSERT INTO comments (art_id, user_id, content)
VALUES
    (1, 4, 'The swirling sky feels like a cosmic dance captured on canvas.'),
    (1, 2, 'The way the village sits under that celestial canopy is magical!'),
    (1, 3, 'Van Gogh''s brushstrokes make the stars seem to dance and twirl.'),
    (9, 1, 'The enigmatic smile on Mona Lisa''s face is a timeless mystery.'),
    (9, 3, 'Da Vinci''s attention to detail in her expression is mesmerizing.'),
    (9, 5, 'The background seems to add depth to her captivating gaze.'),
    (17, 6, 'The rhythmic drips and splashes in Autumn Rhythm create a dynamic energy.'),
    (17, 1, 'Pollock''s abstract expressionism feels like a dance on the canvas.'),
    (17, 4, 'The layers of paint convey a sense of spontaneity and movement.'),
    (25, 3, 'The repetition of the soup cans in Warhol''s artwork challenges our perception of art.'),
    (25, 5, 'Warhol''s depiction elevates everyday objects to iconic status.'),
    (25, 6, 'The Campbell''s Soup Cans embody Warhol''s fascination with consumer culture.'),
    (33, 4, 'The monumental sculpture of David embodies Michelangelo''s mastery of human anatomy.'),
    (33, 3, 'Michelangelo''s attention to detail in David''s muscles and expression is awe-inspiring.'),
    (33, 2, 'David stands as a testament to Michelangelo''s skill and artistic vision.'),
    (41, 1, 'Les Demoiselles d''Avignon revolutionizes art with its radical form and primal energy.'),
    (41, 2, 'Picasso''s fragmentation of figures challenges conventional notions of beauty.'),
    (41, 4, 'The raw power in Les Demoiselles d''Avignon defies traditional ideals and sparks new artistic movements.');

INSERT INTO artTags (art_id, tag_id)
    VALUES
        (1, 1),
        (1, 6),
        (1, 9),
        (2, 1),
        (2, 6),
        (2, 9),
        (3, 1),
        (3, 6),
        (3, 9),
        (4, 1),
        (4, 6),
        (4, 9),
        (4, 11),
        (5, 1),
        (5, 6),
        (5, 9),
        (5, 11),  
        (6, 1),
        (6, 7),
        (6, 9),
        (7, 1),
        (7, 6),
        (7, 9),
        (7, 11),      
        (8, 1),
        (8, 6),
        (8, 9),       
        (9, 1),
        (9, 7),
        (9, 9),
        (10, 2),
        (10, 8),
        (10, 9),
        (11, 1),
        (11, 7),
        (11, 9),
        (12, 1),
        (12, 7),
        (12, 9),
        (13, 1),
        (13, 6),
        (13, 9),
        (13, 11),
        (14, 1),
        (14, 7),
        (14, 9),
        (15, 1),
        (15, 7),
        (15, 9),
        (15, 11),
        (16, 1),
        (16, 6),
        (16, 9),
        (16, 11),
        (17, 1),
        (17, 6),
        (17, 9),
        (18, 1),
        (18, 6),
        (18, 9),
        (19, 1),
        (19, 6),
        (19, 9),
        (20, 1),
        (20, 6),
        (20, 9),
        (21, 1),
        (21, 6),
        (21, 9),
        (22, 1),
        (22, 6),
        (22, 9),
        (23, 1),
        (23, 7),
        (23, 9),
        (24, 1),
        (24, 7),
        (24, 9),
        (25, 1),
        (25, 7),
        (25, 9),
        (26, 1),
        (26, 7),
        (26, 9),
        (27, 1),
        (27, 6),
        (27, 9),
        (28, 1),
        (28, 7),
        (28, 9),
        (29, 1),
        (29, 6),
        (29, 9),
        (30, 1),
        (30, 6),
        (30, 9),
        (31, 1),
        (31, 6),
        (31, 9),
        (32, 1),
        (32, 7),
        (32, 9),
        (33, 7),
        (33, 9),
        (33, 12),
        (34, 1),
        (34, 6),
        (34, 9),
        (35, 7),
        (35, 9),
        (35, 12),
        (36, 1),
        (36, 7),
        (36, 9),
        (37, 7),
        (37, 9),
        (37, 12),
        (38, 1),
        (38, 6),
        (38, 9),
        (39, 7),
        (39, 9),
        (39, 12),
        (40, 7),
        (40, 9),
        (40, 12),
        (41, 1),
        (41, 7),
        (41, 8),
        (41, 9),
        (42, 1),
        (42, 6),
        (42, 8),
        (42, 9),
        (43, 1),
        (43, 7),
        (43, 8),
        (43, 9),
        (44, 1),
        (44, 7),
        (44, 9),
        (45, 1),
        (45, 7),
        (45, 8),
        (45, 9),
        (46, 1),
        (46, 6),
        (46, 8),
        (46, 9),
        (47, 2),
        (47, 6),
        (47, 8),
        (47, 9),
        (48, 1),
        (48, 7),
        (48, 8),
        (48, 9);
