export {default as ArtworkPage} from "./ArtworkPage"
export {default as HomePage} from "./HomePage"
export {default as LoginPage} from "./LoginPage"
export {default as RegisterPage} from "./RegisterPage"
export {default as ProfilePage} from "./ProfilePage"
export {default as CreatePage} from "./CreatePage"
export {default as NotFoundPage} from "./NotFoundPage"